CREATE INDEX newCarId_idx ON newcar_options (newCarId);
CREATE INDEX caroption_idx ON newcar_options (carOption);
CREATE INDEX custId_idx ON sale (customerId);
CREATE INDEX salespersonId_idx ON sale (salespersonId);
CREATE INDEX newcar_idx ON sale (newCarId);
CREATE INDEX usedcar_idx ON sale (usedCarId);
CREATE INDEX insId_idx ON sale (insuranceId);
CREATE INDEX finId_idx ON sale (financingId);
CREATE INDEX registnumber_idx ON sale (registrationNumber);
CREATE INDEX warrantee_idx ON sale (warranteeId);
CREATE INDEX customId_idx ON sale_custom_item (customId);
CREATE INDEX invoicenumber_idx ON sale_custom_item (invoiceNumber);
CREATE INDEX invoicenum_idx ON survey (invoiceNumber);
CREATE INDEX adSeen_idx ON customer (adSeen);
CREATE UNIQUE INDEX salespersonname_idx ON salesperson (firstName, lastName);
CREATE UNIQUE INDEX customerdrivelicense_idx ON customer (driveLicenseNum);
CREATE UNIQUE INDEX newcarvin_idx ON newcar (VIN);
CREATE UNIQUE INDEX usedcarvin_idx ON usedcar (VIN);
CREATE UNIQUE INDEX inspolicycomp_idx ON insurance (policy, company);
CREATE UNIQUE INDEX finpolicycomp_idx ON financing (policy, company);
CREATE UNIQUE INDEX custommenu_idx ON customization_menu (customItem);
CREATE UNIQUE INDEX warrantee_idx ON warrantee (warType);
CREATE UNIQUE INDEX ad_idx ON ad (placedIn, initialDate);
